### ISSUE TITLE
issues with timeout it appears

### ISSUE THREAD

**Issue by wowzaman12** [excid3/logbot#9]
Traceback (most recent call last):
  File "logbot.py", line 351, in <module>
    main()
  File "logbot.py", line 344, in main
    bot.start()
  File "/home/zachthibeau/logbot/ircbot.py", line 247, in start
    SimpleIRCClient.start(self)
  File "/home/zachthibeau/logbot/irclib.py", line 1114, in start
    self.ircobj.process_forever()
  File "/home/zachthibeau/logbot/irclib.py", line 229, in process_forever
    self.process_once(timeout)
  File "/home/zachthibeau/logbot/irclib.py", line 214, in process_once
    self.process_data(i)
  File "/home/zachthibeau/logbot/irclib.py", line 183, in process_data
    c.process_data()
  File "/home/zachthibeau/logbot/irclib.py", line 581, in process_data
    self._handle_event(Event(command, prefix, target, [m]))
  File "/home/zachthibeau/logbot/irclib.py", line 604, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/home/zachthibeau/logbot/irclib.py", line 325, in _handle_event
    if handler[1](connection, event) == "NO MORE":
  File "/home/zachthibeau/logbot/irclib.py", line 1049, in _dispatcher
    getattr(self, m)(c, e)
  File "logbot.py", line 312, in on_pubmsg
    self.write_event("pubmsg", e)
  File "logbot.py", line 212, in write_event
    self.ftp.storbinary("STOR %s" % remote_fname, open(full_fname, "rb"))
  File "/usr/lib/python2.7/ftplib.py", line 460, in storbinary
    self.voidcmd('TYPE I')
  File "/usr/lib/python2.7/ftplib.py", line 249, in voidcmd
    return self.voidresp()
  File "/usr/lib/python2.7/ftplib.py", line 224, in voidresp
    resp = self.getresp()
  File "/usr/lib/python2.7/ftplib.py", line 217, in getresp
    raise error_temp, resp
ftplib.error_temp: 421 Timeout - try typing a little faster next time

this is from the bot I have connected to freenode, the other seperate bot is connected to another irc and hasn't timed out on the ftp uploads.

**Comment by excid3** [comment]
How is the FTP connection from that machine? Seems that it connected properly and it's an FTP configuration issue.

**Comment by wowzaman12** [comment]
never mind other bot just died on me too 

Uploading to FTP...
'index.html'
Traceback (most recent call last):
  File "logbot.py", line 351, in <module>
    main()
  File "logbot.py", line 344, in main
    bot.start()
  File "/home/zachthibeau/test/ircbot.py", line 247, in start
    SimpleIRCClient.start(self)
  File "/home/zachthibeau/test/irclib.py", line 1114, in start
    self.ircobj.process_forever()
  File "/home/zachthibeau/test/irclib.py", line 229, in process_forever
    self.process_once(timeout)
  File "/home/zachthibeau/test/irclib.py", line 214, in process_once
    self.process_data(i)
  File "/home/zachthibeau/test/irclib.py", line 183, in process_data
    c.process_data()
  File "/home/zachthibeau/test/irclib.py", line 600, in process_data
    self._handle_event(Event(command, prefix, target, arguments))
  File "/home/zachthibeau/test/irclib.py", line 604, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/home/zachthibeau/test/irclib.py", line 325, in _handle_event
    if handler[1](connection, event) == "NO MORE":
  File "/home/zachthibeau/test/irclib.py", line 1049, in _dispatcher
    getattr(self, m)(c, e)
  File "logbot.py", line 303, in on_nick
    "%new%" : e.target(),
  File "logbot.py", line 212, in write_event
    self.ftp.storbinary("STOR %s" % remote_fname, open(full_fname, "rb"))
  File "/usr/lib/python2.7/ftplib.py", line 460, in storbinary
    self.voidcmd('TYPE I')
  File "/usr/lib/python2.7/ftplib.py", line 249, in voidcmd
    return self.voidresp()
  File "/usr/lib/python2.7/ftplib.py", line 224, in voidresp
    resp = self.getresp()
  File "/usr/lib/python2.7/ftplib.py", line 217, in getresp
    raise error_temp, resp

**Comment by excid3** [comment]
Any progress on this?

**Comment by wowzaman12** [comment]
sorry about that, just increased to 125 lines and hoping it pans out well, if not then I'll double check the ftpd on my server.

**Comment by excid3** [comment]
Thanks, I'm going to close this ticket as it is definitely working with my configuration every one line.
